[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  tzapu/WiFiManager @ ^2.0.17
  electroniccats/MPU6050 @ ^1.4.2
  slashdevin/NeoGPS @ ^4.2.9

build_flags =
  -D NMEAGPS_PARSE_GGA
  -D NMEAGPS_PARSE_RMC
